### ISSUE TITLE
Live dragging disables grid snapping

### ISSUE THREAD

**Issue by nschoenwald** [Anyndol/FoundryVTT-LiveDrag#1]
The module is awesome! But I have one issue: When live dragging is turned on, the token movement is not snapped to the grid anymore on scenes that have the grid enabled.

**Comment by anyndelworks** [comment]
Hello! Which version of FoundryVTT does this issue happen on? There were a few changes on the way this is handled between 11 and 12 so it'll be helpful to pinpoint the error

**Comment by nschoenwald** [comment]
This is on V12 with latest versions of Foundry, dnd5e and the module. Hope that helps!

**Comment by anyndelworks** [comment]
Apologies for the delay, this should be fixed now. However, keep in mind the default bind to enable live dragging is Shift, which is also the default biding to enable free dragging in Foundry itself.
You'll need to define a new keybind in the controls to use for live dragging, which will make grid snapping work as expected.
